/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-01-30 06:11:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.modelchange;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class confirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

  String contextPath = request.getContextPath();
  
  if (session.getAttribute("login") == null) {

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.jsp");
        return;
      }
      out.write('\n');

  }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/wstyle.css\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( contextPath);
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("<title>Webサイト受付</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"formBgColor\">\n");
      out.write("\n");
      out.write("<table width=\"100%\" height=\"400\" border=\"0\">\n");
      out.write("  <tr>\n");
      out.write("    <td align=\"center\">\n");
      out.write("      <table class=\"headerStyle\">\n");
      out.write("        <tr>\n");
      out.write("          <td align=\"left\" width=\"60%\">Webサイト受付システム  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 登録内容確認</td>\n");
      out.write("          <td align=\"right\" width=\"40%\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 様</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td align=\"right\" width=\"100%\" colspan=\"2\"><a href=\"");
      out.print( contextPath);
      out.write("/LogoutServlet\">ログアウト</a></td>\n");
      out.write("        </tr>\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("      <br/><br/><br/>\n");
      out.write("\n");
      out.write("      <form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/RequestSubmitServlet\" name=\"confirm\">\n");
      out.write("        <table class=\"fullb0\">\n");
      out.write("          <tr>\n");
      out.write("            <td align=\"center\">\n");
      out.write("              <table class=\"formWidth\">\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"5\"> 以下内容で確定いたします。よろしいでしょうか。 </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"2\"> 1.機種 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.deviceName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"2\"> 2.容量 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"20%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.storageSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" GB </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"2\"> 3.色 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.colorName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"2\"> 4.テザリング(オプション) </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> あり ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.tetheringYes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 台 </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"30%\" colspan=\"2\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> なし ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.tetheringNone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 台 </td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                  List<String> telNoList = (List<String>) session.getAttribute("telNoList");

                  if (telNoList != null) {
                    for (int i = 0; i < telNoList.size(); i ++) {
                      session.setAttribute("telNo", telNoList.get(i));

                      if (i == 0) {
                        session.setAttribute("telNoTitle", "対象番号(解約)");
                      }
                      else {
                        session.setAttribute("telNoTitle", "");
                      }
                
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${telNoTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                  <td class=\"normalFont\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${telNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                ");

                    }
                  }
                
      out.write("\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" colspan=\"3\"> 5.ご契約手続き 担当者様情報 </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> 郵便番号 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerZipCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> 所在地 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> 部署 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sectionName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> 担当者様氏名 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.chargeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> ご連絡先電話番号 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerTelNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> e-mailアドレス </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerMailAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"100%\" colspan=\"3\"> <br/> </td>\n");
      out.write("                </tr>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" colspan=\"3\"> 6.仮申込手続き 実施者様情報 </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> ご送付先郵便番号 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicZipCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> ご送付先住所 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> 実施者様氏名 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> ご連絡先電話番号 </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicTelNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"5%\"> <br/> </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"25%\"> e-mailアドレス </td>\n");
      out.write("                  <td class=\"normalFont\" align=\"left\" width=\"70%\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicMailAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("\n");
      out.write("              <br/>\n");
      out.write("\n");
      out.write("              <table class=\"submitButtonWidth\">\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"left\" width=\"250px\">\n");
      out.write("                    <input type=\"hidden\" name=\"customerID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"companyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"entryKind\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"entryKindString\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"deviceName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.deviceName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"storageSize\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.storageSize}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"colorName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.colorName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"tetheringNone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.tetheringNone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"tetheringYes\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.tetheringYes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"customerZipCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerZipCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"customerAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"sectionName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.sectionName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"chargeName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.chargeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"customerTelNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerTelNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"customerMailAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerMailAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"practicZipCode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicZipCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"practicAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"practicName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"practicTelNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicTelNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"hidden\" name=\"practicMailAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.practicMailAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                    <input type=\"submit\"\n");
      out.write("                           value=\"確定\"\n");
      out.write("                           style=\"background-color:#00b0f0;\"\n");
      out.write("                           onmouseover=\"this.style.fontWeight = '900'\" \n");
      out.write("                           onmouseout=\"this.style.fontWeight = 'normal'\">\n");
      out.write("                  </td>\n");
      out.write("                  <td align=\"left\">\n");
      out.write("                    <br/>\n");
      out.write("                  </td>\n");
      out.write("                  <td align=\"right\" width=\"250px\">\n");
      out.write("                    <input type=\"button\"\n");
      out.write("                           value=\"戻る\"\n");
      out.write("                           style=\"background-color:#7f7f7f;\"\n");
      out.write("                           onmouseover=\"this.style.fontWeight = '900'\" \n");
      out.write("                           onmouseout=\"this.style.fontWeight = 'normal'\"\n");
      out.write("                           onClick=\"history.back()\">\n");
      out.write("                  </td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </form>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
