/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-01-30 06:11:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cancellation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

  String contextPath = request.getContextPath();

  String errMsg = (String) request.getAttribute("errMsg");
  if (errMsg == null) {
    errMsg = "";
  }

  if (session.getAttribute("login") == null) {

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.jsp");
        return;
      }
      out.write('\n');

  }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print( contextPath );
      out.write("/wstyle.css\" type=\"text/css\">\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( contextPath );
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("<title>Webサイト受付</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body class=\"formBgColor\">\n");
      out.write("  \n");
      out.write("<table width=\"100%\" height=\"400\" border=\"0\">\n");
      out.write("  <tr>\n");
      out.write("    <td align=\"center\" valign=\"top\">\n");
      out.write("      <table class=\"headerStyle\">\n");
      out.write("        <tr>\n");
      out.write("          <td align=\"left\" width=\"60%\">Webサイト受付システム ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("          <td align=\"right\" width=\"40%\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 様</td>\n");
      out.write("        </tr>\n");
      out.write("        <tr>\n");
      out.write("          <td align=\"right\" width=\"100%\" colspan=\"2\"><a href=\"");
      out.print( contextPath );
      out.write("/LogoutServlet\">ログアウト</a></td>\n");
      out.write("        </tr>\n");
      out.write("      </table>\n");
      out.write("\n");
      out.write("      <br/><br/><br/>\n");
      out.write("\n");
      out.write("      <table class=\"contractMsgWidth\">\n");
      out.write("        <tr>\n");
      out.write("          <td align=\"left\" class=\"errorFont\">");
      out.print( errMsg );
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("      </table>\n");
      out.write("            \n");
      out.write("      <form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/CancellationConfirmServlet\" name=\"changelist\">\n");
      out.write("        <table class=\"contractWidth\">\n");
      out.write("          <tr>\n");
      out.write("            <td align=\"center\">\n");
      out.write("              <table class=\"contractHeaderStyle\">\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"right\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.updateDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("時点 ※金額は税抜価格</td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("\n");
      out.write("              <table class=\"fullb0\">\n");
      out.write("                <tr>\n");
      out.write("                  <td align=\"center\" class=\"tableLineColor\">\n");
      out.write("                    <table class=\"fullb0\">\n");
      out.write("                      <tr>\n");
      out.write("                        <td class=\"tableTitleBgColor\">\n");
      out.write("                          <table class=\"p100b0\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                            <tr>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"4%\">選択</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"4%\">No</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"12%\">ご契約名義</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"10%\">電話番号</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"12%\">機種</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"11%\">ご契約月</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"11%\">ご契約満了月</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"12%\">現在のご利用金額</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"12%\">【機変未実施の場合】<br/>現行機種を継続利用</th>\n");
      out.write("                              <th class=\"tableLineColor\" width=\"1\" height=\"1\"></th>\n");
      out.write("                              <th class=\"s_moji\" align=\"center\" width=\"12%\">【機変未実施の場合】<br/>新機種へ変更後</th>\n");
      out.write("                            </tr>\n");
      out.write("                          </table>\n");
      out.write("                        </td>\n");
      out.write("                      </tr>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                    <table class=\"fullb0\">\n");
      out.write("                      <tr>\n");
      out.write("                        <td>\n");
      out.write("                          ");

                          List<Map> cList = (List<Map>) session.getAttribute("contractDataList");

                          // 契約情報を1行ずつ取得する
                          for (int i = 0; i < cList.size(); i ++) {
                            Map data = cList.get(i);
                            
                            String contractName = (String) data.get("CONTRACT_NAME");
                            String deviceTelNo = (String) data.get("DEVICE_TELNO");
                            String deviceName = (String) data.get("DEVICE_NAME");
                            String startMonth = (String) data.get("START_MONTH");
                            String endMonth = (String) data.get("END_MONTH");
                            String nowPrice = (String) data.get("NOW_PRICE");
                            String continuationPrice = (String) data.get("CONTINUATION_PRICE");
                            String renewalPrice = (String) data.get("RENEWAL_PRICE");
                          
      out.write("\n");
      out.write("                            <tr>\n");
      out.write("                              <td class=\"tableBgColor\">\n");
      out.write("                                <table class=\"p100b0\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n");
      out.write("                                  <tr>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"4%\" align=\"center\">\n");
      out.write("                                      <input type=\"checkbox\" name=\"selectedDevice\" value=\"");
      out.print( deviceTelNo );
      out.write("\">\n");
      out.write("                                    </td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"4%\">");
      out.print( i+1 );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"12%\">");
      out.print( contractName );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"10%\">");
      out.print( deviceTelNo );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"12%\">");
      out.print( deviceName );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"11%\">");
      out.print( startMonth );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"11%\">");
      out.print( endMonth );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"12%\">");
      out.print( nowPrice );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"12%\">");
      out.print( continuationPrice );
      out.write("</td>\n");
      out.write("                                    <td class=\"tableLineColor\" width=\"1\" height=\"1\"></td>\n");
      out.write("                                    <td class=\"s_moji\" align=\"center\" width=\"12%\">");
      out.print( renewalPrice );
      out.write("</td>\n");
      out.write("                                  </tr>\n");
      out.write("                                </table>\n");
      out.write("                              </td>\n");
      out.write("                            </tr>\n");
      out.write("                          ");

                          }
                          
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                      </td>\n");
      out.write("                    </table>\n");
      out.write("                  </td>\n");
      out.write("                </tr>\n");
      out.write("              </table>\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("        <br/>\n");
      out.write("\n");
      out.write("        <table class=\"submitButtonWidth\">\n");
      out.write("          <tr>\n");
      out.write("            <td align=\"left\" width=\"250px\">\n");
      out.write("                <input type=\"hidden\" name=\"customerID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"companyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"entryKind\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKind}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <input type=\"hidden\" name=\"entryKindString\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                <input type=\"submit\"\n");
      out.write("                       value=\"解約\"\n");
      out.write("                       style=\"background-color:#00b0f0;\"\n");
      out.write("                       onmouseover=\"this.style.fontWeight = '900'\" \n");
      out.write("                       onmouseout=\"this.style.fontWeight = 'normal'\">\n");
      out.write("            </td>\n");
      out.write("            <td align=\"left\">\n");
      out.write("              <br/>\n");
      out.write("            </td>\n");
      out.write("            <td align=\"right\" width=\"250px\">\n");
      out.write("              <input type=\"button\"\n");
      out.write("                     value=\"戻る\"\n");
      out.write("                     style=\"background-color:#7f7f7f;\"\n");
      out.write("                     onmouseover=\"this.style.fontWeight = '900'\" \n");
      out.write("                     onmouseout=\"this.style.fontWeight = 'normal'\"\n");
      out.write("                     onClick=\"history.back()\">\n");
      out.write("            </td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("      </form>\n");
      out.write("    </td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
