/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-01-30 06:08:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class submit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPではGET、POST、またはHEADのみが許可されます。 JasperはOPTIONSも許可しています。");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  String contextPath = request.getContextPath();
  if (session.getAttribute("login") == null) {

      out.write('\n');
      if (true) {
        _jspx_page_context.forward("/login.jsp");
        return;
      }
      out.write('\n');

  }

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("  <head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print( contextPath);
      out.write("/wstyle.css\" type=\"text/css\">\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print( contextPath);
      out.write("/js/jquery.min.js\"></script>\n");
      out.write("    <title>Webサイト受付</title>\n");
      out.write("  </head>\n");
      out.write("  <body class=\"formBgColor\">\n");
      out.write("\n");
      out.write("    <table width=\"100%\" height=\"400\" border=\"0\">\n");
      out.write("\n");
      out.write("      ");

        int entryKind = (Integer) session.getAttribute("entryKind");
      
      out.write("\n");
      out.write("\n");
      out.write("      <tr>\n");
      out.write("        <td align=\"center\">\n");
      out.write("          <table class=\"headerStyle\">\n");
      out.write("            <tr>\n");
      out.write("              <td align=\"left\" width=\"60%\">Webサイト受付システム ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 登録完了</td>\n");
      out.write("              <td align=\"right\" width=\"40%\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 様</td>\n");
      out.write("            </tr>\n");
      out.write("            <tr>\n");
      out.write("              <td align=\"right\" width=\"100%\" colspan=\"2\"><a href=\"");
      out.print( contextPath);
      out.write("/LogoutServlet\">ログアウト</a></td>\n");
      out.write("            </tr>\n");
      out.write("          </table>\n");
      out.write("\n");
      out.write("          <br/><br/><br/>\n");
      out.write("\n");
      out.write("          <form method=\"post\" action=\"");
      out.print( contextPath);
      out.write("/MenuServlet\" name=\"submit\">\n");
      out.write("            <table class=\"fullb0\">\n");
      out.write("              <tr>\n");
      out.write("                <td align=\"center\">\n");
      out.write("                  <table class=\"formWidth\">\n");
      out.write("                    <tr>\n");
      out.write("                      <td align=\"center\" width=\"100%\">\n");
      out.write("                        <font class=\"normalFont\">\n");
      out.write("                        <br/>\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.entryKindString}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("の登録が完了いたしました。<br/>\n");
      out.write("                        ");

                          if (entryKind != 3) {
                        
      out.write("\n");
      out.write("                        <br/>\n");
      out.write("                        登録内容につきましては、担当者様および実施者様へ自動送信メールをお送りしておりますのでご確認ください。\n");
      out.write("                        ");

                          }
                        
      out.write("\n");
      out.write("                        <br/><br/>\n");
      out.write("                        </font>\n");
      out.write("                      </td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>\n");
      out.write("\n");
      out.write("                  <br/>\n");
      out.write("\n");
      out.write("                  <table class=\"submitButtonWidth\">\n");
      out.write("                    <tr>\n");
      out.write("                      <td align=\"left\"> <br/> </td>\n");
      out.write("                      <td align=\"center\" width=\"300px\">\n");
      out.write("                        <input type=\"hidden\" name=\"customerID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.customerID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"companyName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.companyName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                        <input type=\"submit\"\n");
      out.write("                               value=\"メニューへ戻る\"\n");
      out.write("                               style=\"background-color:#cc9900;\"\n");
      out.write("                               onmouseover=\"this.style.fontWeight = '900'\" \n");
      out.write("                               onmouseout=\"this.style.fontWeight = 'normal'\">\n");
      out.write("                      </td>\n");
      out.write("                      <td align=\"right\"> <br/> </td>\n");
      out.write("                    </tr>\n");
      out.write("                  </table>\n");
      out.write("                </td>\n");
      out.write("              </tr>\n");
      out.write("            </table>\n");
      out.write("          </form>\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
